platform=chrome
headless=false
remote=true
remoteUrl=http://localhost:4444

browserSize=1920,1080
startMaximized=true
pageLoadStrategy=NORMAL
baseUrl=https://www.google.com
timeout=60000
pollingInterval=500
clickViaJs=false

capabilities.browserName=chrome
#capabilities.browserVersion=latest
#capabilities.platformName=Windows 11